export const FORM_PROJECT = 'FORM_PROJECT';
export const GET_PROJECTS = 'GET_PROJECTS';
export const ADD_PROJECT = 'ADD_PROJECT';
export const FORM_VALIDATION = 'FORM_VALIDATION';
export const OPEN_PROJECT = 'OPEN_PROJECT';
export const DELETE_PROJECT = 'DELETE_PROJECT';